### ISSUE TITLE
What is missing to release a v1.0.0?

### ISSUE THREAD

**Issue by marcjansen** [geostyler/geostyler-cli#16]
Should we do it now?

If not, what do we want in here for a v1.0.0? Are we happy with the syntax cmd line args?

I'd say :shipit: now. As v1.0.0.

**Comment by KaiVolland** [comment]
IMHO we could release a v1.0.0

**Comment by marcjansen** [comment]
Let's do it.

**Comment by KaiVolland** [comment]
Released 1.0.0.:

https://github.com/geostyler/geostyler-cli/releases/tag/v1.0.0

https://www.npmjs.com/package/geostyler-cli
