### ISSUE TITLE
SLD to QML : no display using HEX colors (?)

### ISSUE THREAD

**Issue by vincjo** [geostyler/geostyler-cli#186]
Hello,

I used the CLI to translate an SLD file to QML.
Everything worked well :thumbsup:

But, no symbol displays in QGIS (3.16)

The SLD legend is a categorized polygon, fill color HEX format (#bb000), no outline

The result in the QML file is
````xml
<prop k="color" v="0,0,0,0"/>
````

Expected : 
````xml
<prop k="color" v="51,18,58,255"/>
````

Is there missing support for HEX colors?
I'm gonna try with RGBA format to see if it works better, will tell you (EDIT: no more sucess with RGB / RGBA)

**Comment by vincjo** [comment]
By downgrade from version 1.1.0 to 1.0 of the SLD, everything works correctly.
The `<SvgParameter>` property seems problematic (v1.1.0).
Just had to rename it to `<CssParameter>` (v1.0)

It's OK, thank you for this great tool!

**Comment by jansule** [comment]
Thanks for the info @vincjo! Happy to hear that GeoStyler is useful to you.

We might need to add a flag to the CLI to specify the exact version of the SLD. The parser itself supports this already. I just created a new issue for that (https://github.com/geostyler/geostyler-cli/issues/187).

BTW, there is a CodeSprint coming in June and we are still looking for more participants. In case you are interested, some more information is provided on geostyler.org

**Comment by vincjo** [comment]
thanks for your return jansule 

I will take a look at it
