### ISSUE TITLE
Specify Version of SLD

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler-cli#187]
Currently, the geostyler-cli does not allow to specify the SLD version for the geostyler-sld-parser. We might want to add a flag here.

Based on the info from https://github.com/geostyler/geostyler-cli/issues/186

**Comment by vincjo** [comment]
Hello, 

Maybe the version can be parsed directly by Geostyler, as it is specified in the SLD header
````xml
<StyledLayerDescriptor version="1.1.0">
````
But maybe I'm wrong !

**Comment by jansule** [comment]
You are right in general. The problem is that we cannot derive the SLD version when writing from geostyler-style to SLD. Here, we went for consistency between reading/writing instead of auto detection.

**Comment by vincjo** [comment]
got it, thx

**Comment by jansule** [comment]
Solved in https://github.com/geostyler/geostyler-cli/pull/323
