### ISSUE TITLE
Handle Windows Paths

### ISSUE THREAD

**Issue by geographika** [geostyler/geostyler-cli#194]
The following command, using Windows style paths:

```
npm start -- -s sld -t geostyler -o C:\Temp C:\Temp\itasca.sld
```

Currently returns:

```
× Error during translation of file "C:\\Temp\\itasca.sld": Error: ENOENT: no such file or directory, open 'C:\Temp\Temp\itasca.geostyler'
```

Fix on way that will convert Windows paths to Linux paths to avoid this error.

**Comment by KaiVolland** [comment]
Fixed with https://github.com/geostyler/geostyler-cli/pull/195
