### ISSUE TITLE
Create tests for CLI

### ISSUE THREAD

**Issue by KaiVolland** [geostyler/geostyler-cli#337]
Currently there are no tests for the functionality of the geostyler-cli.

It would be nice if we can find a way to test:
- all the option parameters
- expected structure of nested files and folders
- behaviour of mixed files in a folder (e.g. folder includes *.txt. *.jpg files)

IMHO the content of the created files should not be tested as this is in the responsibility of the parsers themselves.

Maybe @marcjansen has an idea of how we could test this as this is outside of the JS scope and I have not much experience on testing things on the filesystem base.

**Comment by geographika** [comment]
Several of the above are covered in the new test script in https://github.com/geostyler/geostyler-cli/pull/343

**Comment by KaiVolland** [comment]
I close this as @geographika thankfully added tests some time ago.
