### ISSUE TITLE
Conversion to an output file writes to a directory instead of a file

### ISSUE THREAD

**Issue by geographika** [geostyler/geostyler-cli#344]
This issue is linked to changes in https://github.com/geostyler/geostyler-cli/pull/335
The code below checks if the output parameter exists and if it is a file, however when writing an output this file won't exist, and `targetIsFile` is always `false`.

```
  // Try to define type of target (file or dir).
  let targetIsFile = false;
  const outputExists = existsSync(outputPath);
  if (outputExists) {
    targetIsFile = lstatSync(outputPath).isFile();
  }
```

This leads to the output being written to subdirectories based on the input e.g.

`npm start -- -s qgis -t qgis -o output.sld testdata/point_simple.qml` creates `output.qml/point_simplepoint.qml`

The workflow in https://github.com/geostyler/geostyler-cli/pull/343 highlights this issue. 
See for example the output at https://github.com/geographika/geostyler-cli/actions/runs/4925040568/jobs/8798798475#step:8:13

I'm unsure of the best approach to fix this. Would simply checking for an extension of the output parameter to set `targetIsFile` be enough?

**Comment by geographika** [comment]
@KaiVolland - the issue is the output could be specified as a file or folder. As they might not yet exist I can only think of checking for a file extension in the`-o` parameter. A folder could contain `.` though e.g.`/tmp/09.05.2023/folder`
Maybe we could require the specified output root folder to exist?
It would also be good to add a test to https://github.com/geostyler/geostyler-cli/pull/343 for processing a folder. Should I add some test files for this?

**Comment by KaiVolland** [comment]
We could also check if the -o parameter contains at least one `path.sep` (`/`) if not we assume it is a file. And if you want a folder to be create at root level it has to start with `./`?

**Comment by jansule** [comment]
@geographika is this issue solved?

**Comment by geographika** [comment]
@jansule - yes fixed in https://github.com/geostyler/geostyler-cli/pull/347/files. Closing. 

```js
  // Assume the target is the same as the source
  let targetIsFile = sourceIsFile;
```
