### ISSUE TITLE
missing binaries

### ISSUE THREAD

**Issue by hambsch** [geostyler/geostyler-cli#413]
Hi,

could you possibly provide windows binaries for the latest releases (4.1.0)?

Thanks

**Comment by KaiVolland** [comment]
There is currently a bug in the pipeline that prevents that binaries from being supplied as an asset at the release.

As a workaround you can clone the repo and build the binaries yourself with:
`npm i && npm run build-binaries`

**Comment by KaiVolland** [comment]
The latest release `4.1.2` includes the binaries again.
